services:
  elasticsearch:
    image: elasticsearch:8.10.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
      
  career:
    build:
      context: ./career
    ports:
      - "8001:80"
    env_file:
      - .env
    depends_on:
      - elasticsearch

  readerclub:
    build:
      context: ./readerclub
    ports:
      - "8000:80"
    env_file:
      - .env