services:
  elasticsearch:
    image: elasticsearch:8.10.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
      
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://elasticsearch:9200 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  career:
    build:
      context: ./career
    volumes:
      - ./career:/app
    ports:
      - "8001:81"
    env_file:
      - .env
    depends_on:
      - elasticsearch
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"  
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy



  readerclub:
    build:
      context: ./readerclub
    volumes:
      - ./readerclub:/app
      - ./readerclub/staticfiles:/app/staticfiles
    ports:
      - "8000:80"
    env_file:
      - .env