FROM python:3.12-alpine
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 8001
CMD ["sh", "entrypoint.sh"]
# CMD ["gunicorn", "--bind", "0.0.0.0:8001", "career.wsgi:application"]
