# Generated by Django 5.1.5 on 2025-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='serial_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='serial_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
