# Generated by Django 5.1.5 on 2025-02-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examportol', '0002_alter_category_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='serial_number',
            new_name='category_code',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='serial_number',
            new_name='question_code',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='question_subject',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='category',
            new_name='subject_category',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='serial_number',
            new_name='subject_code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
    ]
