# Generated by Django 5.1.4 on 2025-02-05 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegesDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('college_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(default='0000000000', max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('college_name', models.CharField(default='Unknown College', max_length=255)),
                ('dob', models.DateField(default=datetime.date(2000, 1, 1))),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(default='USR00001', editable=False, max_length=10, unique=True)),
            ],
        ),
    ]
