# Generated by Django 5.1.4 on 2025-02-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDB',
            new_name='StudentsDB',
        ),
    ]
