# Generated by Django 5.1.4 on 2025-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_rename_userdb_studentsdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdb',
            name='username',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
