# Generated by Django 5.1.4 on 2025-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_alter_studentsdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsdb',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
