# Generated by Django 5.1.4 on 2025-02-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_alter_studentsdb_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdb',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
