# Generated by Django 5.1.4 on 2025-02-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_studentsdb_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsDB',
            new_name='UsersDB',
        ),
    ]
