# Generated by Django 5.1.4 on 2025-01-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('course_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
