# Generated by Django 5.1.4 on 2025-01-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_backend', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
