# Generated by Django 5.1.4 on 2025-01-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_backend', '0003_alter_course_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_name', models.CharField(max_length=100, unique=True)),
                ('difficulty_code', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
    ]
