# Generated by Django 5.1.5 on 2025-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Name', max_length=100)),
                ('description', models.TextField(default='Unknown Description', max_length=1000)),
                ('user_profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('hand_written_review', models.ImageField(blank=True, null=True, upload_to='hand_written_review')),
                ('company_name', models.CharField(default='Unknown Company', max_length=100)),
                ('degination', models.CharField(default='Unknown Designation', max_length=100)),
                ('package', models.IntegerField(default=0)),
                ('batch', models.CharField(default='Unknown Batch', max_length=100)),
                ('degree', models.CharField(default='Unknown Degree', max_length=100)),
                ('branch', models.CharField(default='Unknown Branch', max_length=100)),
            ],
        ),
    ]
