# Generated by Django 4.2.11 on 2025-02-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementstories',
            old_name='degination',
            new_name='designation',
        ),
    ]
