FROM python:3.12-alpine

WORKDIR /app

# Install dependencies: Java, Node.js, FreeType, and build tools
RUN apk add --no-cache \
        openjdk17-jre-headless \
        nodejs \
        npm \
        freetype-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        gcc \
        musl-dev \
        python3-dev \
        make \
        g++ \
    && pip install --upgrade pip
RUN pip install --no-cache-dir mysql-connector-python    

# Set Java environment variables for Alpine
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH="$JAVA_HOME/bin:$PATH"

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --timeout=1000 --index-url https://mirrors.aliyun.com/pypi/simple/

# Copy the application code and entrypoint script
COPY . .
COPY deventrypoint.sh /app/deventrypoint.sh
RUN chmod +x /app/deventrypoint.sh

# Expose the port for development
EXPOSE 8000

CMD ["sh", "deventrypoint.sh"]
