services:
  readerclub:
    build:
      context: ./readerclub
    volumes:
      - ./readerclub:/app
      - ./readerclub/staticfiles:/app/staticfiles
    ports:
      - "8000:80"
    env_file:
      - .env


  career:
    build:
      context: ./career
    volumes:
      - ./career:/app
      - ./career/staticfiles:/app/staticfiles
    ports:
      - "8001:80"

    env_file:
      - .env


