# Generated by Django 5.1.4 on 2025-02-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_registration', '0002_alter_registration_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='ExamRegistration',
        ),
    ]
