# Generated by Django 5.1.4 on 2025-02-12 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_registration', '0003_rename_registration_examregistration'),
        ('examportol', '0005_alter_category_category_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField()),
                ('payment', models.CharField(default='INR 999', max_length=20)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='examportol.category')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='examportol.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamRegistration',
        ),
    ]
